#! /bin/bash

# using sourcing
. ././helpers/functions.sh



choice=$(zenity --list \
  --height="250"\
  --width="350"\
  --cancel-label="Exit" \
  --title="Table $table Menu" \
  --column="Option" \
     "Delete All" \
     "Delete All By Column" \
     "Delete By Column" \
     "Main Menu" \
     "Exit")

        if [ $? -eq 1 ]
        then
            echo -e "${Green}Exited..${ColorReset}" #exit from database
            exit
        fi

case $choice in 
    "Delete All"). ./user_operations/dml-operations/delete_statments/select_all_from_table.sh $dbName $table;;
    "Delete All By Column"). ./user_operations/dml-operations/delete_statments/select_all_from_table_by_column.sh $dbName $table;;
    "Delete By Column"). ./user_operations/dml-operations/delete_statments/select_by_key_from_table.sh $dbName $table;;
    "Main Menu") mainMenu;;
    5) echo -e "${Green}Exited..${ColorReset}";exit;; #exit from database
    *) echo -e "${RED}invalid choice, try again ... you must choose only from the above list${ColorReset}";mainMenu #Call it again
esac 